spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spot
        username: test1234
        password: DPM15thspot!
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update  # 주의: 프로덕션 환경에서는 'validate' 사용 권장
        properties:
            hibernate:
                use_sql_comments: true
        defer-datasource-initialization: true
    sql:
        init:
            mode: never  # 필요한 경우 'never'로 변경


server:
    port: 8080