#!/bin/sh

PROJECT_ROOT=$(git rev-parse --show-toplevel)

# part1
stagedFiles=$(git diff --staged --name-only)

# part2
echo "Running spotlessApply. Formatting code..."
cd $PROJECT_ROOT && ./gradlew spotlessApply

if [ $? -ne 0 ]; then
  echo "Spotless apply failed!"
  exit 1
fi

# part3
for file in $stagedFiles; do
  if test -f "$file"; then
    git add $file
  fi
done