package org.depromeet.spot.usecase.service.fake;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

import org.depromeet.spot.domain.stadium.Stadium;
import org.depromeet.spot.domain.team.BaseballTeam;
import org.depromeet.spot.usecase.port.out.team.HomeTeamRepository;

public class FakeHomeTeamRepository implements HomeTeamRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);

    private final Map<Stadium, List<BaseballTeam>> homeTeamMap =
            Collections.synchronizedMap(new HashMap<>());

    @Override
    public List<BaseballTeam> findAllHomeTeamByStadium(Long stadiumId) {
        return homeTeamMap.entrySet().stream()
                .filter(entry -> stadiumId.equals(entry.getKey().getId()))
                .flatMap(entry -> entry.getValue().stream())
                .collect(Collectors.toList());
    }

    @Override
    public Map<Stadium, List<BaseballTeam>> findAllStadiumHomeTeam() {
        return homeTeamMap;
    }
}
