# Pull Request size labels
- name: "size/XS"
  color: "A2D9A1"
  description: "Extra Small size PR."
- name: "size/S"
  color: "73BFF2"
  description: "Small size PR."
- name: "size/M"
  color: "FFEB3B"
  description: "Medium size PR."
- name: "size/L"
  color: "FF9800"
  description: "Large size PR."
- name: "size/XL"
  color: "F44336"
  description: "Extra Large size PR."