server:
    port: 8080
    shutdown: graceful

spring:
    # 서브모듈 profile
    profiles:
        active: dev
        group:
            local:
                - jpa
                - aws
                - jwt
                - oauth
            dev:
                - jpa
                - aws
                - jwt
                - oauth
                - monitoring
            prod:
                - jpa
                - aws
                - jwt
                - oauth
                - sentry
                - monitoring
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 30MB

springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui.html

decorator:
    datasource:
        p6spy:
            enable-logging: true

# spring actuator
management:
    server:
        port: 9292
    endpoint:
      health:
          show-details: always
    endpoints:
        prometheus:
            enabled: true
        web:
            exposure:
                include: "*"
---
spring:
    config:
        activate:
            on-profile: local
---
spring:
    config:
        activate:
            on-profile: dev
---
spring:
    config:
        activate:
            on-profile: prod

decorator:
    datasource:
        p6spy:
            enable-logging: false

springdoc:
    swagger-ui:
        enabled: false