server:
    port: 8080
    shutdown: graceful

spring:
    # 서브모듈 profile
    profiles:
        active: local
        group:
          local:
              - jpa
              - ncp
              - jwt
              - kakao
          dev:
              - jpa
              - ncp
              - jwt
              - kakao
          prod:
              - jpa
              - ncp
              - jwt
              - kakao
              - sentry
    # swagger를 이용해 API 명세서 생성
    doc:
        swagger-ui:
            path: /swagger-ui.html

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 30MB