server:
  port: 8080
  shutdown: graceful

spring:
  # 서브모듈 profile
  profiles:
    include:
        - jpa
        - ncp
        - jwt
        - kakao
  # swagger를 이용해 API 명세서 생성
  doc:
    swagger-ui:
      path: /swagger-ui.html