server:
    port: 8080
    shutdown: graceful

spring:
    # 서브모듈 profile
    profiles:
        active: local
        group:
            local:
                - jpa
                - aws-credentials
            dev:
                - jpa
                - monitoring
            prod:
                - jpa
                - sentry
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 30MB

springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui.html

decorator:
    datasource:
        p6spy:
            enable-logging: true

# spring actuator
management:
    server:
        port: 9292
    endpoint:
      health:
          show-details: always
    endpoints:
        prometheus:
            enabled: true
        web:
            exposure:
                include: "*"

# secret manager
aws:
    secretsmanager:
        name: spot-local-secrets
cloud:
    aws:
        region:
            static: ap-northeast-2
        stack:
            auto: false
---
spring:
    config:
        activate:
            on-profile: local
aws:
    secretsmanager:
        name: spot-local-secrets
---
spring:
    config:
        activate:
            on-profile: dev
aws:
    secretsmanager:
        name: spot-dev-secrets
---
spring:
    config:
        activate:
            on-profile: prod
aws:
    secretsmanager:
        name: spot-prod-secrets

decorator:
    datasource:
        p6spy:
            enable-logging: false

springdoc:
    swagger-ui:
        enabled: false